*  Deal with the fact that data types come from root. *  Make buildall fail if one of the builds fails.

diff --git a/plugins/buildall b/plugins/buildall
--- a/plugins/buildall
+++ b/plugins/buildall
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e              # Exit on errors.
+
 
 target=$1
 if [ x$ROOTSYS = x ]
