Mere with master - this also catches changes to the filter.

diff --git a/plugins/buildall b/plugins/buildall
--- a/plugins/buildall
+++ b/plugins/buildall
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e              # Exit on errors.
+
 
 target=$1
 if [ x$ROOTSYS = x ]
@@ -11,7 +13,7 @@ fi
 (cd firstof; autoreconf -i; ./configure -prefix=$target; make clean all install)
 (cd map; autoreconf -i; ./configure -prefix=$target; make clean all install)
 (cd radwareio; autoreconf -i; ./configure -prefix=$target; make clean all install)
-(cd rootFilterFormat;mkdir m4; autoreconf -i; \
+(cd rootFilterFormat; autoreconf -i; \
     ./configure -prefix=$target --with-rootsys=$ROOTSYS; make clean all install)
 
 #
